name: wireguard-gui # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Wireguard client GUI made with nextauri
description: |
  Provide a Wireguard client GUI for easy profile management
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  wireguard-gui:
    extensions: [gnome]
    command: /usr/bin/wireguard-gui
    desktop: /usr/share/applications/com.wireguard-gui.gg
    common-id: com.wireguard-gui.gg
    plugs:
      - network # This plug grants network access
      - network-bind # This plug is often needed for applications that listen on ports
      - desktop # This plug grants access to the desktop environment
      - desktop-legacy # This plug grants access to legacy desktop environments
      - wayland # This plug grants access to Wayland
      - x11 # This plug grants access to X11

parts:
  # Install wireguard from apt
  wireguard:
    plugin: nil
    override-build: |
      wget http://archive.ubuntu.com/ubuntu/pool/main/w/wireguard/http://archive.ubuntu.com/ubuntu/pool/main/w/wireguard/wireguard-tools_1.0.20210914-1ubuntu3_amd64.deb
      dpkg -x http://archive.ubuntu.com/ubuntu/pool/main/w/wireguard/wireguard-tools_1.0.20210914-1ubuntu3_amd64.deb $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - dpkg
      - wget

  wireguard-gui:
    plugin: nil
    override-build: |
      wget http://archive.ubuntu.com/ubuntu/pool/main/b/bash/bash_5.1-3ubuntu1_amd64.deb
      dpkg -x bash_5.1-3ubuntu1_amd64.deb $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - dpkg
      - wget
