name: wireguard-gui # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Wireguard client GUI made with nextauri
description: |
  Provide a Wireguard client GUI for easy profile management
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  wireguard-gui:
    # extensions: [gnome]
    command: desktop-launch $SNAP/usr/bin/wireguard-gui
    desktop: usr/share/applications/wireguard-gui.desktop
    common-id: com.wireguard-gui.gg
    # environment:
    #   LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib
    plugs:
      - home # Access to user's home directory
      - network # This plug grants network access
      - network-bind # This plug is often needed for applications that listen on ports
      - desktop # This plug grants access to the desktop environment
      - desktop-legacy # This plug grants access to legacy desktop environments
      - wayland # This plug grants access to Wayland
      - x11 # This plug grants access to X11

parts:
  # Install wireguard and zenity from apt
  dependencies:
    plugin: nil
    stage-packages:
      - wireguard
      - zenity
      - pkexec

  # Install wireguard-gui from github
  wireguard-gui:
    plugin: nil
    override-build: |
      wget https://github.com/leon3s/wireguard-gui/releases/download/0.1.0-stable/wireguard-gui_0.1.0_amd64.deb
      dpkg -x wireguard-gui_0.1.0_amd64.deb $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - dpkg
      - wget
