name: wireguard-gui
base: core22
version: '0.1.9'
summary: WireGuard client GUI made with nextauri
icon: src-tauri/icons/128x128.png
description: |
  Provides a WireGuard client GUI for easy profile management
  
  This snap uses the network-control interface to manage WireGuard
  connections without requiring pkexec or sudo, making it work
  properly in strict snap confinement.
grade: stable
source-code: https://github.com/leon3s/wireguard-gui
confinement: strict
architectures:
  - build-on: amd64

apps:
  wireguard-gui:
    command: usr/bin/wireguard-gui
    common-id: com.wireguard-gui.gg
    extensions: [gnome]
    desktop: usr/share/applications/wireguard-gui.desktop
    environment:
      # Enable WireGuard operations via network-control interface
      WG_QUICK_USERSPACE_IMPLEMENTATION: wireguard-go
    plugs:
      - home
      - network
      - network-manager
      - network-control
      - modem-manager
      - network-setup-observe
      - firewall-control
      - hardware-observe
      - network-setup-control
      - login-session-observe
      - network-observe
      - desktop
      - desktop-legacy

parts:
  rust:
    plugin: nil
    build-packages:
      - curl
    override-build: |
      # Install Rust toolchain
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
      craftctl default
    build-environment:
      - PATH: "${HOME}/.cargo/bin:${PATH}"

  wireguard-gui:
    after: [rust]
    plugin: npm
    source: .
    npm-include-node: true
    npm-node-version: "20.11.0"
    override-build: |
      # Set up Rust environment
      export PATH="${HOME}/.cargo/bin:${PATH}"
      
      # Install dependencies
      npm install
      
      # Build Tauri app
      npm run tauri build
      
      # Install files
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/bin
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/share/applications
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/share/icons/hicolor/128x128/apps
      
      # Copy binary
      cp src-tauri/target/release/wireguard-gui ${SNAPCRAFT_PART_INSTALL}/usr/bin/
      
      # Copy icon
      cp src-tauri/icons/128x128.png ${SNAPCRAFT_PART_INSTALL}/usr/share/icons/hicolor/128x128/apps/wireguard-gui.png
      
      # Create desktop file
      cat > ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/wireguard-gui.desktop << DESKTOP
[Desktop Entry]
Version=1.0
Type=Application
Name=WireGuard GUI
Comment=Manage WireGuard VPN profiles
Exec=wireguard-gui
Icon=\${SNAP}/usr/share/icons/hicolor/128x128/apps/wireguard-gui.png
Terminal=false
Categories=Network;System;
DESKTOP

    build-packages:
      - wget
      - file
      - pkg-config
      - libssl-dev
      - libgtk-3-dev
      - libwebkit2gtk-4.1-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - patchelf
      - libjavascriptcoregtk-4.1-dev
      - libsoup-3.0-dev
      
    stage-packages:
      - wireguard-tools
      - libwebkit2gtk-4.1-0
      - libjavascriptcoregtk-4.1-0
      - libayatana-appindicator3-1
      - libsoup-3.0-0
      
    prime:
      - -usr/share/doc
      - -usr/share/man

# Mount webkit2gtk and set up WireGuard directories
layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1

