# Build the application

name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest
    container: rust:1.90.0-alpine3.22

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      # Cache Rust
      - uses: actions/cache@v3
        with:
          path: ./src-tauri/target
          key: ubuntu-latest-${{ hashFiles('./src-tauri/Cargo.lock') }}

      # Cache Rust
      - uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ubuntu-latest-${{ hashFiles('./src-tauri/Cargo.lock') }}

      # Cache Node
      - uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ubuntu-latest-${{ hashFiles('./package-lock.json') }}

      # Cache Next.js
      - uses: actions/cache@v3
        with:
          path: ./src-next/.next
          key: ubuntu-latest

      - name: Install dependencies
        run: |
          apk add --update alpine-sdk musl-dev g++ make openssl-dev git perl build-base dpkg bash
          rustup target add x86_64-unknown-linux-musl

      - name: Install Node.js v20 LTS
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Rust with Clippy
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install Tauri dependencies
        run: |
          sudo apt-get update
          sudo apt install --reinstall ca-certificates
          sudo update-ca-certificates -f
          sudo apt-get install javascriptcoregtk-4.1 libsoup-3.0 webkit2gtk-4.1 libayatana-appindicator3-dev librsvg2-dev -y

      - name: Install node dependencies
        run: npm install

      - name: Build application
        run: npm run tauri build -- --verbose --target x86_64-unknown-linux-musl
